### ISSUE TITLE
Self hosting docs lead to 404

### ISSUE THREAD

**Issue by AlexXi19** [mixpanel/tracking-proxy#12]
Self hosting docs lead to 404

**Comment by tdumitrescu** [comment]
Which doc? Got any more details than this?

**Comment by AlexXi19** [comment]
![image](https://github.com/mixpanel/tracking-proxy/assets/68758451/f12bcb15-49e7-44b4-ac53-a4ee05f1b5e0)

**Comment by tdumitrescu** [comment]
Thanks, link should be fixed now
