### ISSUE TITLE
Anonymising Ip's

### ISSUE THREAD

**Issue by mhaamann** [mixpanel/tracking-proxy#3]
Hi Mixpanel,

Do you have a suggestion for a Nginx configuration that could anonymise the users IP? Due to GDPR concerns we would prefer not to forward this and instead rely on sending a unique user identifier instead via the SDK.

Or can we simply leave out the IP from the configuration or would this hit some sort of connection limitter based per ip?

**Comment by ak--47** [comment]
@mhaamann 

the canonical way to do this is to pass `{ ip : false }` to the mixpanel library itself

```javascript
mixpanel.init(token, {ip : false});
```

mixpanel's ingestion servers always discards IP addresses; this stop them from being processed at all (for the purpose of geolocation, etc...)

[docs](https://docs.mixpanel.com/docs/tracking/how-tos/privacy-friendly-tracking#disabling-geolocation)
